### ISSUE TITLE
[SauceLabs] Massive Barrier to Entry for Contributions

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-ui#312]
Code changes have the potential to ripple changes across snapshot artifacts. To get a PR to pass, a contributor has to force an update of the artifacts. *External contributors have no way of updating these artifacts without SauceLabs access.*

Access is behind strict lock and key, which introduces an massive barrier to entry for contributing to HelixUI.

This should be corrected as soon as possible.

**Comment by 100stacks** [comment]
Resolved #687
Fixed #694
