### ISSUE TITLE
Creating tabs in empty tabset with Js 

### ISSUE THREAD

**Issue by Flexin1981** [HelixDesignSystem/helix-ui#516]
## Describe the Bug
The bug appears when there are no elements in a tabset and a new tab is added dynamically with JS, this stops the tabs working correctly. 

## Steps to Reproduce

```
    <div class="hxPanel hxTabbed">
    <hx-tabset>
        <hx-tablist id="tablist">
        </hx-tablist>
        <hx-tabcontent id="tabcontent">
        </hx-tabcontent>
    </hx-tabset>
    </div>
```
Now add an element to the tablist.
```
let t = document.createElement('hx-tab');
t.innerText = name;
document.getElementById('tablist').appendChild(t) 
```
The correct attributes are not added to the element.

## Expected behavior
```
    <div class="hxPanel hxTabbed">
    <hx-tabset>
        <hx-tablist id="tablist">
            <hx-tab>Ssl</hx-tab>
        </hx-tablist>
        <hx-tabcontent id="tabcontent">
            <hx-tabpanel>...</hx-tabpanel>
        </hx-tabcontent>
    </hx-tabset>
    </div>
```

Now add an element to the tablist.

```
let t = document.createElement('hx-tab');
t.innerText = name;
document.getElementById('tablist').appendChild(t) 
```
You Should see that the new element has the correct attributes and the tab system works.

**Comment by CITguy** [comment]
@Flexin1981, can you reproduce the issue in a CodePen example? You can use https://codepen.io/pen?template=NYYzpE as a starter.

I'm not able to reproduce the error even going as far back as `helix-ui v0.2.0` (released Jan 31, 2018).
https://codepen.io/CITguy/pen/QXjNXy

If you aren't seeing `role="tablist"` on `<hx-tablist>` (or `role="presentation"` on `<hx-tabcontent>`), it might be that they've not upgraded. If that's the case, please check that you're successfully loading the HelixUI and polyfills JavaScript assets.

**Comment by Flexin1981** [comment]
So if you note, that the in the expected behaviour, when you click the button to adda a new tab, in the html even though I have not specified them in the element i get attributes added like "aria-controls" and others and is effecting how the tabs work.

So if I try to build the entire thing dynamically then I get the bug behaviour if I add a tab first statically then it works from that point forward.

## Expected Behaviour
https://codepen.io/flexin1981/pen/EBVedx

##  Bug Behaviour
https://codepen.io/flexin1981/pen/qzOyWo

**Comment by CITguy** [comment]
Ah, ok. 

### Workaround
Currently, you'll have to run `update()` on the `<hx-tabset>` element after you add your `<hx-tab>` + `<hx-tabpanel>` pairs (FYI: _every_ tab needs to have an associated tabpanel).

### Proper Fix
In `helix-ui`, we'll need to:

* apply mutation observers to `<hx-tablist>` and `<hx-tabcontent>`, so that we can watch for new elements and `update()` automatically
* `HXTabsetElement._setupIds()` should be renamed to `HXTabsetElement._updateA11y()`
* `HXTabsetElement.update()` should also call `_updateA11y()` to configure aria attributes on tabs and panels
* update `<hx-tabset>` to support less than optimal markup on connect
    * don't initialize if `<hx-tablist>` or `<hx-tabcontent>` is missing
        * `hx-tabset` (empty)
        * `hx-tabset > hx-tablist:empty` (no `hx-tabcontent`, no `hx-tab` elements)
        * `hx-tabset > hx-tabcontent:empty` (no `hx-tablist`, no `hx-tabpanel` elements)
    * don't initialize if `<hx-tab>` and `<hx-tabpanel>` elements are missing
        * `hx-tabset > hx-tablist:empty + hx-tabcontent:empty` (no `hx-tab` or `hx-tabpanel` elements)
    * initialize as much as possible if panels and tabs are uneven
        * open tab with current index, if present
            * `hx-tabset > hx-tablist:empty + hx-tabcontent` (more panels than tabs)
        * open panel with current index, if present
            * `hx-tabset > hx-tablist + hx-tabcontent:empty` (more tabs than panels)

**Comment by CITguy** [comment]
work prioritized in SURF-1756
