### ISSUE TITLE
Not able to Navigate between one or more tab panels

### ISSUE THREAD

**Issue by pras7430** [HelixDesignSystem/helix-ui#758]
## Describe the Bug
I can see below error in chrome console

Failed to construct 'CustomElement': The result must not have attributes.

## Steps to Reproduce
Imported Tab-Set component in the Angular 9 application.

Not able to Navigate between one or more tab panels. it is happening after the new release
I just used the snippet code sample given on Helix.

e.g
<hx-tabset>
  <hx-tablist>
    <hx-tab>First</hx-tab>
    <hx-tab>Second</hx-tab>
    <hx-tab>Third</hx-tab>
  </hx-tablist>
  <hx-tabcontent>
    <hx-tabpanel>...</hx-tabpanel>
    <hx-tabpanel>...</hx-tabpanel>
    <hx-tabpanel>...</hx-tabpanel>
  </hx-tabcontent>
</hx-tabset>

## Expected behavior
it should navigate between one or more tab panels.

## Screenshots
<img width="1779" alt="Screenshot 2020-08-27 at 3 24 08 PM" src="https://user-images.githubusercontent.com/62294382/91426495-38833b00-e87a-11ea-8ede-044332456762.png">

## Environment
Please complete the following information:

 - Device: [MacBook Pro]
 - OS:  MAC 
 - Browser: Chrome
 - Version: Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by 100stacks** [comment]
Hi @pras7430, thank you for submitting this issue.  Was this working before and not does not?

Also, can you provide a code snippet please.

**Comment by pras7430** [comment]
Hi @100stacks, 
Yes, it was working before.

below snippet code, we are using

<div class="hxRow">
  <div class="hxCol">
    <hx-tabset current-tab="0">
      <hx-tablist>
        <hx-tab id="tab-1" current="true"> Monitors</hx-tab>
        <hx-tab id="tab-2">Resources</hx-tab>
      </hx-tablist>
      <hx-tabcontent>
        <hx-tabpanel id="panel-1" open>
          Monitors
        </hx-tabpanel>
        <hx-tabpanel id="panel-2">  
Resources
        </hx-tabpanel>
      </hx-tabcontent>
    </hx-tabset>
  </div>
</div>



showing the same problem, though I tried the given sample on the helix  

<hx-tabset>
  <hx-tablist>
    <hx-tab>First</hx-tab>
    <hx-tab>Second</hx-tab>
    <hx-tab>Third</hx-tab>
  </hx-tablist>
  <hx-tabcontent>
    <hx-tabpanel>...</hx-tabpanel>
    <hx-tabpanel>...</hx-tabpanel>
    <hx-tabpanel>...</hx-tabpanel>
  </hx-tabcontent>
</hx-tabset>

**Comment by pras7430** [comment]
Even I tried with a given sample on the helix, showing the same issue.

```
<hx-tabset>
  <hx-tablist>
    <hx-tab>First</hx-tab>
    <hx-tab>Second</hx-tab>
    <hx-tab>Third</hx-tab>
  </hx-tablist>
  <hx-tabcontent>
    <hx-tabpanel>...</hx-tabpanel>
    <hx-tabpanel>...</hx-tabpanel>
    <hx-tabpanel>...</hx-tabpanel>
  </hx-tabcontent>
</hx-tabset>
```

**Comment by 100stacks** [comment]
Hi @pras7430, based on your error dump above, it may have something to do with Angular's and HelixUI component lifecycle methods generating this error.

I ask @BY00565233 to reach out to you to assist.

**Comment by pras7430** [comment]
Thank you @100stacks.

**Comment by BY00565233** [comment]
As per the information provided, I have tried to replicate the issue. The issue is working fine except angular 9. As per my findings this issue might be part of angular life-cycle, specific to custom elements. I am working on this issue and will post the updates if any.

**Comment by 100stacks** [comment]
Hi @pras7430, I'm working on a solution for this issue.

I'm testing it with @BY00565233 first.  If all goes well, we'll push an RC release early next week for you to test/verify.

**Comment by pras7430** [comment]
Thanks, @100stacks, and @BY00565233

**Comment by 100stacks** [comment]
Hi, @pras7430, I just pushed a release candidate - **HelixUI-v1.1.0-rc.0** - for this issue.

#### When you have an opportunity, please test patch: https://www.npmjs.com/package/helix-ui/v/1.1.0-rc.0

Thanks 👍

**Comment by pras7430** [comment]
Hi @100stacks,

 I'll update it here soon.

Thanks

**Comment by 100stacks** [comment]
Ok, thanks for the feedback @pras7430! 😄
