### ISSUE TITLE
Broken styling of disabled Dropdown Select in Chromium-based browsers

### ISSUE THREAD

**Issue by CITguy** [HelixDesignSystem/helix-ui#766]
## Describe the Bug
Lengthy values in a disabled Dropdown Select aren't covered by the "grabber" portion of the facade bg (see screenshot).

## Steps to Reproduce

1. Go to https://helixdesignsystem.github.io/helix-ui/components/dropdown-select/test.html#test-misc
2. look at `lengthy option - disabled` test

## Expected behavior
The "grabber" portion of the facade should have a solid background to cover the text of the selected value (as it does in `lengthy option - enabled` test).

## Screenshots

![CleanShot 2020-09-23 at 12 33 37](https://user-images.githubusercontent.com/545605/94048375-08578b00-fd99-11ea-8a1a-3fc7c5223d74.png)
1. text and icon are overlapping with no solid background to cover value (as it does in the enabled state)

## Environment
Please complete the following information:

 - Device: Laptop (MBP 16")
 - OS: macOS
 - Browser:
    - Chrome (v85)
    - Edge (v85)
    - Opera (v71)

**Comment by 100stacks** [comment]
@CITguy thanks for the feedback...how's it going?!

I'm not able to replicate your issue on large and small screen format:

## Large Format Screen

![Screen Shot 2020-09-24 at 3 51 54 PM](https://user-images.githubusercontent.com/10120600/94199143-fac80100-fe7d-11ea-9d1c-61ca90cb9abd.png)

## Small Format Screen

![Screen Shot 2020-09-24 at 3 55 02 PM](https://user-images.githubusercontent.com/10120600/94199402-5eeac500-fe7e-11ea-9ea6-2181c14387b7.png)

**Comment by CITguy** [comment]
I'm able to replicate the issue on two separate Macbook Pro laptops; one 16" one 15" (both on macOS 10.15.6).

It only seems to apply to Chromium-based browsers (Safari and Firefox don't have any issue).

![CleanShot 20200925-203027](https://user-images.githubusercontent.com/545605/94327027-009d0f80-ff6e-11ea-9e70-4f67506688cd.gif)

(Additionally, you may want to ensure that your `<select>` element is `opacity: 1` when `:disabled`.  Chrome seems to apply a 70% opacity on disabled `<select>` as of some recent version; maybe when they updated form control appearances earlier in 2020.)

**Comment by 100stacks** [comment]
Ok thanks for the above description, @CITguy.

I'm on an older version of Chrome, so that explains why I wasn't able to replicate it.  I'll capture this in an issue.

**Comment by 100stacks** [comment]
Hi @CITguy, a solution has been published with the latest release - https://www.npmjs.com/package/helix-ui/v/1.1.0.

Thanks 👍
