### ISSUE TITLE
Generalize Top Navigation Implementation

### ISSUE THREAD

**Issue by michaelmang** [HelixDesignSystem/helix-ui#776]
## Describe the Problem
The top navigation stylesheet styles the top navigation dropdown and menu using an id: https://github.com/HelixDesignSystem/helix-ui/blob/master/src/scss/components/topnav/index.scss#L102.

The issue with this is that it does not allow for a top navigation implementation with multiple dropdown menus:

![Screen Shot 2020-10-19 at 2 37 09 PM](https://user-images.githubusercontent.com/22566333/96497390-9c8e0400-1218-11eb-9c1a-73ae745a7a7c.png)

## Steps to Reproduce

Add multiple `hx-discolsure` menus with id="topnav-menu"`

## Expected behavior
Multiple top navigation dropdowns may be used without interfering with each other's state/styling.

## Helix Version
 - 1.1.0-rc.0

**Comment by 100stacks** [comment]
@michaelmang, thank you for submitting this issue and the great feedback!

We'll push a fast-follow to address this limitation.

**Comment by 100stacks** [comment]
Hi @michaelmang, a solution has been published with the latest release - https://www.npmjs.com/package/helix-ui/v/1.1.0.

Thanks 👍
